# Kustomization raiz del directorio base
# Incluye todos los componentes del ecosistema RehabiAPP
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - network/default-deny.yaml
  - api/
  - data/
  - mobile-backend/
  - postgresql/
  - mongodb/
labels:
  - pairs:
      project: rehabiapp
      managed-by: kustomize
    includeSelectors: false
    includeTemplates: true
